// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/a-aslani/golang_agency_clean_architecture/internal/newsletter/model/contract (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination mocks/repository_mock.go -package mocks github.com/a-aslani/golang_agency_clean_architecture/internal/newsletter/model/contract Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/a-aslani/golang_agency_clean_architecture/internal/newsletter/model/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindOneSubscriberByEmail mocks base method.
func (m *MockRepository) FindOneSubscriberByEmail(arg0 context.Context, arg1 string) (*entity.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneSubscriberByEmail", arg0, arg1)
	ret0, _ := ret[0].(*entity.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneSubscriberByEmail indicates an expected call of FindOneSubscriberByEmail.
func (mr *MockRepositoryMockRecorder) FindOneSubscriberByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneSubscriberByEmail", reflect.TypeOf((*MockRepository)(nil).FindOneSubscriberByEmail), arg0, arg1)
}

// FindOneSubscriberByID mocks base method.
func (m *MockRepository) FindOneSubscriberByID(arg0 context.Context, arg1 string) (*entity.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneSubscriberByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneSubscriberByID indicates an expected call of FindOneSubscriberByID.
func (mr *MockRepositoryMockRecorder) FindOneSubscriberByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneSubscriberByID", reflect.TypeOf((*MockRepository)(nil).FindOneSubscriberByID), arg0, arg1)
}

// SaveSubscriber mocks base method.
func (m *MockRepository) SaveSubscriber(arg0 context.Context, arg1 *entity.Subscriber) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSubscriber", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSubscriber indicates an expected call of SaveSubscriber.
func (mr *MockRepositoryMockRecorder) SaveSubscriber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSubscriber", reflect.TypeOf((*MockRepository)(nil).SaveSubscriber), arg0, arg1)
}
