global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'agency'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['newsletter_service:8000', 'file_uploader_service:8001', 'support_service:8002', 'project_service:8003']